### PR TITLE
HTML5 inside! Please pull...

### PR DESCRIPTION
**Pull request by valpackett**
...and release a new minor version.

I'm developing [a web framework](https://github.com/myfreeweb/ringfinger) that really needs that thing :-)

### CODE REVIEW

**Comment by weavejester** [comment]
I don't understand the point of adding this metadata to the predicates. Could you explain?

**Comment by valpackett** [comment]
With this metadata, web frameworks can automatically insert
client-side validations with form helpers. So,

```
(defresource "contacts" {:store mongodb :pk :name}
  [:name string? "wtf"]
  [:site url? "not a url"])
```

will automatically render the input for the second field with type="url"

On Jun 12, 2011, at 3:07 AM, weavejester
reply@reply.github.com
wrote:

**Comment by weavejester** [comment]
Ah, I see. However, I believe this violates the principle of simplicity, in the sense that these functions are now doing two things - acting as predicates _and_ supplying data about input types.

If we have two things we want to do, we should create two functions. For brevity, we may decide to create a compound function to wrap our two simple functions, but those simple functions must exist individually.

So in this case, you might want to construct something like:

```
(defn url [name error]
  {:name name
   :type "url"
   :validation url?
   :error error})
```

And then use the resulting map to define both the input type and the validation.

**Comment by valpackett** [comment]
That'd be too much code, which will violate the principle of simplicity
even more.

Metadata is completely unobtrusive. And that's essentially the exact
same thing - validation, but on the client side.

Input types _are_ validations at their core, browser vendors may (or
may not) implement additional functionality, eg. different keyboards in
iOS.

**Comment by weavejester** [comment]
In my view, simplicity does not necessarily mean reducing code; it means producing functions that perform only one task.

In this case, the predicates are designed to test whether a value is valid. Adding additional metadata does not help the predicates validate values; it performs another function entirely.

You're more than welcome to take the code from Valip and use it in your own projects (under the open source EPL license), or build another validation library on the top of Valip.

However, I'm going to be a opinionated here and say that I'm not going to add HTML5 input metadata to Valip itself. It doesn't fit in with Valip's design goals.

**Pull request closed without merging**
